#!/bin/bash
# Memory consolidation for capability-evolver optimization
# Creates monthly summaries from daily logs

YEAR_MONTH="${1:-2026-03}"
OUTPUT_DIR="memory/monthly"
DAILY_DIR="memory/daily"

mkdir -p "$OUTPUT_DIR"

echo "Consolidating logs for $YEAR_MONTH..."
echo "======================================"

# Find all daily files for the month
FILES=$(find "$DAILY_DIR" -name "${YEAR_MONTH}-*.md" | sort)

if [ -z "$FILES" ]; then
    echo "No files found for $YEAR_MONTH"
    exit 1
fi

OUTPUT_FILE="$OUTPUT_DIR/${YEAR_MONTH}-summary.md"

# Create header
echo "# Monthly Summary: $YEAR_MONTH" > "$OUTPUT_FILE"
echo "**Generated by capability-evolver memory consolidation**" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Overview" >> "$OUTPUT_FILE"
echo "- Files consolidated: $(echo "$FILES" | wc -l)" >> "$OUTPUT_FILE"
echo "- Date range: $(echo "$FILES" | head -1 | sed 's/.*\///' | sed 's/.md//') to $(echo "$FILES" | tail -1 | sed 's/.*\///' | sed 's/.md//')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Consolidate content
FILE_COUNT=0
TOTAL_LINES=0

for file in $FILES; do
    if [ -f "$file" ]; then
        FILENAME=$(basename "$file" .md)
        LINES=$(wc -l < "$file")
        
        echo "## $FILENAME" >> "$OUTPUT_FILE"
        echo "**Lines**: $LINES" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        # Add first 10 lines as preview
        head -10 "$file" | sed 's/^/    /' >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "---" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        FILE_COUNT=$((FILE_COUNT + 1))
        TOTAL_LINES=$((TOTAL_LINES + LINES))
    fi
done

echo "## Statistics" >> "$OUTPUT_FILE"
echo "- Total files: $FILE_COUNT" >> "$OUTPUT_FILE"
echo "- Total lines: $TOTAL_LINES" >> "$OUTPUT_FILE"
echo "- Average lines per day: $((TOTAL_LINES / FILE_COUNT))" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Consolidated on: $(date)*" >> "$OUTPUT_FILE"

echo "Consolidation complete!"
echo "Output: $OUTPUT_FILE"
echo "Files processed: $FILE_COUNT"
echo "Total lines: $TOTAL_LINES"